version: '3.7'
services:
  mongodb_container:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  client_container:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
      - magic_mirror_api

  magic_mirror_api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 6600:6600
    depends_on:
      - mongodb_container
    env_file: ./server/.env

volumes:
  mongodb_data_container:
  redis_data_container:
