version: '3.7'
services:
  redis_container:
    image: redis:latest
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redis_data_container:/db

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  client_container:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
      - server_container

  server_container:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    depends_on:
      - mongodb_container
    env_file: ./server/.env

volumes:
  mongodb_data_container:
  redis_data_container:
